<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_s-image</name>
   <tag></tag>
   <elementGuidId>ab63586e-60b2-4ce6-a8c0-f0b786791329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/div/div/span/div/div/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2c406db-d29f-4448-b618-30ec3e9ee4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>72ddb0e2-a4f7-4fc8-9770-c5d9710ca3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL320_.jpg</value>
      <webElementGuid>4648e17d-9d73-407d-b8f6-09f1657aa03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL320_.jpg 1x, https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL480_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL640_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL800_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL960_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>d932359f-587b-4f0f-9192-d68ab0bc65c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sponsored Ad - Cetaphil Hydrating Eye Gel-Cream, With Hyaluronic Acid, 0.5 fl oz, Brightens and Smooths Under Eyes, 24 Hou...</value>
      <webElementGuid>9ae94ccc-e051-4497-87f3-3d35bdd768ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f3bb9088-7691-4538-820c-85873b8c17ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>445c4a40-87ff-4f3e-9001-0dc9a583a18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5b6948d5-a3f5-4a4a-b790-2f9bf33bb4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-4-of-24 sg-col-4-of-12 s-result-item s-asin sg-col-4-of-16 AdHolder sg-col s-widget-spacing-small sg-col-4-of-20&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot;]/div[@class=&quot;rush-component s-expand-height&quot;]/div[@class=&quot;rush-component s-featured-result-item s-expand-height&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-expand-height puis-include-content-margin puis puis-v2rh3j15wdcp4q29xeaptoa72x6 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section a-spacing-base&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-spacing-small s-height-equalized puis puis-v2rh3j15wdcp4q29xeaptoa72x6&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-square-aspect&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>e67af7a9-ede6-4d5a-bdb1-7a91c4bef869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/div/div/span/div/div/div/span/a/div/img</value>
      <webElementGuid>258c6871-5230-4924-b894-a57686c6a46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sponsored Ad - Cetaphil Hydrating Eye Gel-Cream, With Hyaluronic Acid, 0.5 fl oz, Brightens and Smooths Under Eyes, 24 Hou...']</value>
      <webElementGuid>0ba9d1e0-1fa9-47fa-8d8d-e55833b7d9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>9a44c398-6248-403a-90b5-1aad352d5518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71C7kw5xwXL._AC_UL320_.jpg' and @alt = 'Sponsored Ad - Cetaphil Hydrating Eye Gel-Cream, With Hyaluronic Acid, 0.5 fl oz, Brightens and Smooths Under Eyes, 24 Hou...']</value>
      <webElementGuid>1b1f5fdf-c225-4c69-85f7-ccd404a040e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
